version: '3.9'

services:

  nginx:
    cap_add:
      - SYS_MODULE
    build:
      context: .
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /lib/modules:/lib/modules
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
